const Book = [
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Classic",
    criteria1: 9,
    criteria2: 1,
    criteria3: 5,
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
    criteria1: 8,
    criteria2: 2,
    criteria3: 3,
  },
  {
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    criteria1: 7,
    criteria2: 2,
    criteria3: 4,
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Coming-of-age",
    criteria1: 6,
    criteria2: 2,
    criteria3: 1,
  },
  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    genre: "Thriller",
    criteria1: 9,
    criteria2: 1,
    criteria3: 2,
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    criteria1: 8,
    criteria2: 1,
    criteria3: 3,
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    criteria1: 9,
    criteria2: 2,
    criteria3: 4,
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
    criteria1: 8,
    criteria2: 1,
    criteria3: 5,
  },
  {
    title: "The Hound of the Baskervilles",
    author: "Arthur Conan Doyle",
    genre: "Mystery",
    criteria1: 7,
    criteria2: 1,
    criteria3: 3,
  },
  {
    title: "Neuromancer",
    author: "William Gibson",
    genre: "Science Fiction",
    criteria1: 8,
    criteria2: 2,
    criteria3: 4,
  },
  {
    title: "The Adventures of Tom Sawyer",
    author: "Mark Twain",
    genre: "Adventure",
    criteria1: 6,
    criteria2: 2,
    criteria3: 2,
  },
  {
    title: "The Maltese Falcon",
    author: "Dashiell Hammett",
    genre: "Mystery",
    criteria1: 6,
    criteria2: 2,
    criteria3: 3,
  },
  {
    title: "Snow Crash",
    author: "Neal Stephenson",
    genre: "Science Fiction",
    criteria1: 9,
    criteria2: 2,
    criteria3: 5,
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    criteria1: 7,
    criteria2: 1,
    criteria3: 4,
  },
  {
    title: "Emma",
    author: "Jane Austen",
    genre: "Romance",
    criteria1: 8,
    criteria2: 2,
    criteria3: 3,
  },
];

module.exports = Book;
